#!/usr/bin/perl
use strict;
use File::Find;
use File::Slurp;
use Term::ANSIColor;
use feature 'switch';

# Load the M7 configuration
use lib '/opt/vpls/m7/lib/perl/modules';
use M7Config;
use M7Socket;

# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ #
# Init Info \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ #
#
# Provides:          m7d
# Default-Start:     3 4 5
# Short-Description: M7 Socket.IO Server
# Description:       Server process to run facilitate real-time communication
#					 between the dashboard and cluster nodes.

# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ #
# Chkconfig Info \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ #
#
# m7-ws-server:      M7 Socket.IO Server
# chkconfig:         345 97 03
# description:       Server process to run facilitate real-time communication
#					 between the dashboard and cluster nodes.
# processname:       m7-ws-server
# pidfile:           /var/run/m7-ws-server.pid

# Load the configuration values
my $m7c = M7Config->new();
my $m7s = M7Socket->new();
my $retval = undef;

# Set the service variables
my %service = (
	'name'	=> $m7c->get('sio_name'),
	'pid'	=> $m7c->get('sio_pid'),
	'lock'	=> $m7c->get('sio_lock')
);

sub success {
	print color 'green';
	print "SUCCESS\n";
	print color 'reset';
}
sub failed {
	my ($current_status) = @_;
	print color 'red';
	print "FAILED\n";
	print color 'reset';
	$m7s->serviceUpdate('socketio', $current_status);
}

sub status {
	my $pid_run = undef;
	my $pid_num = undef;

	# Check if the PID file exists
	my $pid_status = (-f $service{pid} ? 1 : undef);
	
	# If it exists get the PID number and status
	if ($pid_status) {
		$pid_num = read_file($service{pid});
		$pid_run = kill('0', $pid_num);
	}
	
	# If the process is running
	if ($pid_run) {
		print $service{name} . " (pid " . $pid_num . ") is running...\n"; 
		$retval = 0;
	} else {
		print $service{name} . " is stopped\n"; 
		$retval = 1;
	}
}

sub start {
	
	# If the process is already running, show the status
	if (-f $service{pid}) {
		&status;
		exit $retval;
	}
	print "Starting the " . $service{name} . " daemon: ";
	
	system('nohup node ~/bin/' . $service{name} . ' "' . $m7c->get('sio_ip') . '" "' . $m7c->get('sio_port') . '" "' . $m7c->get('sio_proto') . '" "' . $m7c->get('sio_secret') . '" >/dev/null 2>&1 &') == 0
		or &failed('Failed to start ' . $service{name} . ' process');
	
	# Get the PID of the process and create the pidfile
	my $pid_num = qx(pidof node);
	open(my $pid_fh, '>', $service{pid})
		or &failed('stopped', 'Failed to open PID file');
	print $pid_num $service{pid};
	close($pid_fh);
	
	# Create the lockfile
	open(LOCKFILE, '>' . $service{lock})
		or &failed('stopped', 'Failed to create lock file');
		
	# Process started
	&success;
}

sub stop {
	
	# If the lock file doesn't exist, print the status and exit
	unless (-e $service{lock}) {
		&status;
		exit $retval;
	}
	
	# Get the PID
	my $pid_num = read_file($service{pid});
	
	# Stop the process
	print "Stopping the " . $service{name} . " daemon: ";
	kill('15', $pid_num)
		or &failed('Failed to terminate ' . $service{name} . 'process - PID ' . $pid_num);
	
	# Delete the PID and lock files
	unlink($service{pid})
		or &failed('running', 'Failed to remove PID file');
	unlink($service{lock})
		or &failed('running', 'Failed to remove lock file');
		
	# Process stopped
	&success;
}

sub restart {
	&stop;
	&start;
}

sub usage {
	print "Usage: service " . $service{name} . " {start|stop|restart|status}\n";
	exit 1;
}

given ($ARGV[0]) {
	when('status')	{ &status;	 }
	when('start')	{ &start;	 }
	when('stop')	{ &stop;	 }
	when('restart') { &restart;  }
	default 		{ &usage;	 }	
}

exit $retval;